### ISSUE TITLE
The UI sliders are always stuck on zero

### ISSUE THREAD

**Issue by BlitzKraft** [nicolasbrailo/VlcFreemote#12] opened 2018-09-25 18:07 UTC
[Screenshot with the issue](https://i.imgur.com/ki8Rz14.png).

In the screen shot, the video is about 10 mins in of 40 mins. Volume is at 50%. Display shows them both stuck at zero. They actually do control the seek and volume when used. For example, when I move the slider to anywhere, the appropriate volume is set, but the display goes back to zero. The rest of the UI works fine.

**Comment by nicolasbrailo** [comment] 2018-09-26 14:59
Thanks for the report @BlitzKraft! Any chance you could post a copy of VLC's status page? ( Should be http://10.0.0.193:8080/requests/status.xml )

**Comment by BlitzKraft** [comment] 2018-09-27 04:41
[This is the pastebin](https://pastebin.com/ETGgpDn6).

**Comment by nicolasbrailo** [comment] 2018-12-02 19:08
I'm afraid I can't reproduce this issue. Even forcing VLC to output the XML from the pastebin, I get correct behavior on my test devices. Any other tips to reproduce it?

**Comment by BlitzKraft** [comment] 2018-12-02 19:11
I can't recall what version of the app I was using, when I faced this issue. I haven't used it since. I'll try it again.

**Comment by nicolasbrailo** [comment] 2018-12-02 19:16
Thanks @BlitzKraft. I haven't updated the app since September, so I don't expect any changes. Any tip to reproduce will be welcome though!

**Comment by nicolasbrailo** [comment] 2018-12-08 10:02
Since I can't find a way to reproduce it, I'll close this one for now

**Closed by nicolasbrailo** 2018-12-08 10:02 UTC
